server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: eureka-clieant-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql：//localhost:3306/

